# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yumme
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ndhs-api
service: ndhs-api

provider:
  name: aws
  runtime: python3.13
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:ap-northeast-2:<AWS_ACCOUNT_ID>:table/MyTable

functions:
  api:
    handler: lambda_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
