org: yumme
app: ndhs-api
service: ndhs-api

provider:
  name: aws
  runtime: python3.13
  region: ap-northeast-2

functions:
  api:
    handler: lambda_handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
